name: Build

on:
  workflow_dispatch:
    inputs:
      versionTag:
        description: Version
        required: true
        type: string

jobs:
  build:
    name: Build package and draft release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout changes
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.ref }}

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 'lts/*'
        registry-url: https://registry.npmjs.org/

    - name: Bump version to ${{ github.event.inputs.versionTag }}
      run: |
        npm version ${{ github.event.inputs.versionTag }} --allow-same-version --no-git-tag-version

    - name: Build package
      run: |
        npm install
        npm run build
        git status

    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: 'Build ${{ github.event.inputs.versionTag }}'
        tagging_message: ${{ github.event.inputs.versionTag }}
        skip_fetch: true
        skip_checkout: true

    - name: Create draft release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.event.inputs.versionTag }}
        draft: true
        prerelease: ${{ contains(github.event.inputs.versionTag, '-rc.') }}
        files: dist/*
        fail_on_unmatched_files: true

    - name: Purge jsDelivr CDN cache
      run: |
        curl https://purge.jsdelivr.net/gh/maxherrmann/blu@latest/dist/blu.esm.min.js
        curl https://purge.jsdelivr.net/gh/maxherrmann/blu@latest/dist/blu.esm.min.js.map
        curl https://purge.jsdelivr.net/gh/maxherrmann/blu@latest/dist/blu.umd.min.js
        curl https://purge.jsdelivr.net/gh/maxherrmann/blu@latest/dist/blu.umd.min.js.map